Add OtacilioN to the list
github/brasil pull request #48
Opened 2023-06-27 16:09 UTC by OtacilioN

add me as maintainer increasing regional diversity of maintainers list 

I'm currently maintaining:

- [Brasilino](https://github.com/OtacilioN/Brasilino)
- [Awesome Hacktoberfest](https://github.com/OtacilioN/awesome-hacktoberfest)
- [Funny Algorithms](https://github.com/ReciHub/FunnyAlgorithms)

### Por favor, confirme se este pull request atende aos seguintes requisitos:

- [x] Segui as diretrizes de contribuição: https://github.com/github/brasil/blob/main/CONTRIBUTING.md.

### Qual alteração você está propondo?

- [x] Adicionar/atualizar projeto(s) de código aberto
- [x] Adicionar/atualizar mantenedor(es)

---

### Adicionar/atualizar projeto(s) de código aberto

- [x] O projeto foi construído no Brasil ou recebe contribuições significativas do Brasil
- [x] O projeto possui pelo menos 100 pessoas marcando como favorito (stargazers)

**Por que este projeto de código aberto deveria ser apresentado?**

> Por favor, substitua esta linha por uma explicação do motivo pelo qual você acredita que essas alterações devem ser feitas.

### Adicionar/atualizar mantenedor(es)

- [x] A localização do mantenedor em seu perfil do GitHub indica que é no Brasil
- [x] O mantenedor aprovou que este PR seja incluído no site

**Quais projeto(s) de código aberto o indivíduo mantém?**

- [Brasilino](https://github.com/OtacilioN/Brasilino)
- [Awesome Hacktoberfest](https://github.com/OtacilioN/awesome-hacktoberfest-2022)
- [Funny Algorithms](https://github.com/ReciHub/FunnyAlgorithms)

### Algo que não se encaixa perfeitamente nas opções acima

- [ ] Minhas edições sugeridas não se referem a uma página existente, ou pelo menos não a uma única página

> Por favor, substitua esta linha por uma explicação das alterações propostas.

---

**Obs: fecharemos o seu PR sem comentários se você não marcar as caixas acima e fornecer TODAS as informações solicitadas.**

2023-06-27 16:20 UTC, OtacilioN commented on website/data/open-source/projects.yml
> -Machine Learning:
A aba de machine learning estava duplicada com o msm projeto, aproveitei e corrigi

2023-06-27 18:16 UTC, AndreaGriffiths11 requested changes
Hi @OtacilioN obrigada for the additions, could you ensure this projects have open source licenses applied

2023-06-27 20:36 UTC, OtacilioN commented
Thanks @AndreaGriffiths11.

Reviewed. 

- Brasilino was under GPL3 ✅ 
- Awesome Hacktoberfest was under Public Domain License (CC0 1.0 Universal), but missing LICENSE file (added now) ✅ 
- Funny Algorithm was unlicensed, now under public domain (CC0 1.0 Universal) ✅

2023-06-27 20:40 UTC, OtacilioN commented
Also, these projects:

        - `yagasaki7k/website-essentials`
		- Project has less than 100 stars
	- `yagasaki7k/website-runinlinux`
		- Project doesn't have a license
		- Project has less than 100 stars
	- `raulpesilva/re-state`
		- Project has less than 100 stars
		
that's failing the pipeline wasn't added by me. should I remove them to make the pipeline pass? @AndreaGriffiths11

2023-06-28 03:57 UTC, juanpflores commented
@AndreaGriffiths11 Otacilio is a GH Campus Experts as well. He has a ton of great resources as well.

2023-06-28 16:25 UTC, AndreaGriffiths11 submitted a review, later dismissed

2023-06-28 16:37 UTC, AndreaGriffiths11 approved these changes

2023-06-28 16:37 UTC, merged

2023-07-02 19:00 UTC, OtacilioN commented
@ErickSimoes and @CaioCordeiro since you both are Brazilian and you both are maintainers of ReciHub/FunnyAlgorithms a qualified repository, you both can add a pull request adding yourselves to the list of Brazilian maintainers.

@ErickSimoes you can also add [Ultrasonic](https://github.com/ErickSimoes/Ultrasonic) to the list since is a qualified project.

2023-07-04 13:18 UTC, ErickSimoes commented
Thanks @OtacilioN for the tip!

I'll add it right now!

2023-07-04 14:16 UTC, CaioCordeiro commented
Just opened the PR. 
Thanks, @OtacilioN !